# Generated by Django 4.1.3 on 2024-01-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce.category",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="specifications",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
