# Generated by Django 4.1.3 on 2024-01-17 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="item_images"),
        ),
        migrations.AddField(
            model_name="item",
            name="thumbnail",
            field=models.ImageField(default="default.jpg", upload_to="item_thumbnails"),
        ),
        migrations.AddField(
            model_name="item",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="total_weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(model_name="order", name="item",),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("confirmed", "CONFIRMED"),
                    ("shipped", "SHIPPED"),
                    ("delivered", "DELIVERED"),
                    ("cancelled", "CANCELLED"),
                    ("returned", "RETURNED"),
                    ("refunded", "REFUNDED"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecommerce.item"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.category",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="colors",
            field=models.ManyToManyField(related_name="items", to="ecommerce.color"),
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(
                through="ecommerce.OrderItem", to="ecommerce.item"
            ),
        ),
    ]
