# Generated by Django 4.1.3 on 2024-01-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_currency_transaction_item_currency"),
    ]

    operations = [
        migrations.DeleteModel(name="Transaction",),
    ]
