# Generated by Django 4.1.3 on 2024-01-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_employeeprofile_customerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="user_type",
            field=models.CharField(
                choices=[("vendor", "VENDOR"), ("customer", "Customer")],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="dept",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
