# Generated by Django 4.1.3 on 2024-02-09 12:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_comment_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to=core.models.upload_image_path
            ),
        ),
    ]
